#if DEBUG
import Foundation

// The 50-preset inline DEBUG library is a long parameters-only data table (no logic), so the
// file/enum length rules don't meaningfully apply here.
// swiftlint:disable file_length

/// Research Step 3/4 — v0 preset format for the native feedback engine. Parameters
/// only (no shader code, no expressions); versioned; original Vibrdrome format
/// (not `.milk`). DEBUG-only — the prototype loads presets from the inline JSON in
/// `PermissivePresetLibrary` so **no `.json` is bundled into the app**.
/// Human-readable copies live in `docs/permissive-visualizer/presets/*.json`.
struct PermissivePreset: Identifiable, Codable {
    let version: Int
    let id: String
    let name: String
    let author: String
    let license: String?
    let decay: Float
    let zoom: Float
    let rotate: Float
    let paletteIndex: Int
    let paletteShift: Float
    let pulseScale: Float
    let zoomBass: Float
    let rotateTreble: Float
    let pulseBass: Float
    // Step 4 — optional visual-depth knobs (decodeIfPresent → 0, so the format stays
    // backward-compatible at version 1).
    let bloomStrength: Float
    let waveformStrength: Float
    // Step 6 — optional flow-engine knobs. `flow > 0` switches the feedback pass from the
    // legacy center rotate/zoom to curl-noise advection; the rest shape flow/beat/colour.
    // All decode with safe defaults (decodeIfPresent), so version stays 1.
    let flow: Float        // flow-field advection strength, 0 = legacy center path
    let flowScale: Float   // spatial frequency of the flow field
    let beatFlow: Float    // beatPulse → flow acceleration
    let beatBloom: Float   // beatPulse → bloom kick
    let hueDrift: Float    // colour drift speed (cosine-palette path)
    // Step 7 — waveform-into-feedback (the fine-line MilkDrop look). The audio waveform is
    // drawn as thin bright geometry into the feedback texture; the warp/flow/tunnel loop
    // then pulls it into filaments. All optional/defaulted, version stays 1.
    let waveStyle: Int     // 0 = off, 1 = circular, 2 = horizontal scope
    let waveAmp: Float     // waveform displacement amount
    let waveBright: Float  // line brightness (the glow)
    let tunnel: Float      // zoom-in pull that turns the lines into a tunnel/spiral
    // Phase 7b — bilateral mirror + vibrance.
    let symmetry: Int      // 0 = off, 1 = vertical (L/R) mirror, 2 = quad (4-way)
    let vibrance: Float    // saturation + brightness multiplier (1 = neutral)
    // Phase 7c "wow" — field spin + beat-driven waveform amplitude burst.
    let spin: Float        // field rotation speed (time + beat driven)
    let beatWave: Float    // beatPulse → waveform amplitude burst (the kick "explosion")
    // Phase 8 — polar warp (the vortex). warpMode 1 selects polar; swirl/swirlFreq shape it.
    let swirl: Float       // radius-modulated angle swirl amount (the spiral)
    let swirlFreq: Float   // spatial frequency of the swirl
    let warpMode: Int      // 0 = curl-flow, 1 = polar warp (hero)
    // Phase 8b — kaleidoscope wedge count for the present-time polar fold (0 = off).
    let kaleido: Int
    // Phase 8c — radial spectrum spokes (Radiant): ray count (0 = off) + radial bar length.
    let spokes: Int
    let spokeLen: Float
    // Phase 8c-2 — inject spokes into the feedback field (1) for bloom + trails, vs present-only (0).
    let spokeInject: Int
    // Phase 8c-3 — whirlpool: center-weighted rotational warp (0 = off).
    let whirl: Float
    // Phase 9 — polar lattice (intersecting rings/lines → moiré) + colour wash overlay.
    let lattice: Float
    let latticeR: Float
    let latticeA: Float
    let wash: Float
    // Phase 10 — fractal fold (nested mandala) + Voronoi liquid cells.
    let fractal: Int
    let cells: Float
    // Phase 11 — logarithmic (Droste) spiral warp (0 = off).
    let spiral: Float
    // Phase 12 — angular: mirror-tiling grid, pixelate blocks, Truchet maze (0 = off).
    let tile: Float
    let pixelate: Float
    let truchet: Float
    // Phase 13 — outside-the-box layers (0 = off).
    let tunnel3d: Float
    let plasma: Float
    let phyllo: Float
    let ripple: Float
    let hex: Float
    let chroma: Float

    init(version: Int, id: String, name: String, author: String, license: String?,
         decay: Float, zoom: Float, rotate: Float, paletteIndex: Int, paletteShift: Float,
         pulseScale: Float, zoomBass: Float, rotateTreble: Float, pulseBass: Float,
         bloomStrength: Float = 0, waveformStrength: Float = 0,
         flow: Float = 0, flowScale: Float = 2.5, beatFlow: Float = 0,
         beatBloom: Float = 0, hueDrift: Float = 0,
         waveStyle: Int = 0, waveAmp: Float = 0, waveBright: Float = 0, tunnel: Float = 0,
         symmetry: Int = 0, vibrance: Float = 1.0,
         spin: Float = 0, beatWave: Float = 0,
         swirl: Float = 0, swirlFreq: Float = 8, warpMode: Int = 0,
         kaleido: Int = 0, spokes: Int = 0, spokeLen: Float = 0, spokeInject: Int = 0,
         whirl: Float = 0,
         lattice: Float = 0, latticeR: Float = 12, latticeA: Float = 16, wash: Float = 0,
         fractal: Int = 0, cells: Float = 0, spiral: Float = 0,
         tile: Float = 0, pixelate: Float = 0, truchet: Float = 0,
         tunnel3d: Float = 0, plasma: Float = 0, phyllo: Float = 0,
         ripple: Float = 0, hex: Float = 0, chroma: Float = 0) {
        self.version = version; self.id = id; self.name = name; self.author = author
        self.license = license; self.decay = decay; self.zoom = zoom; self.rotate = rotate
        self.paletteIndex = paletteIndex; self.paletteShift = paletteShift
        self.pulseScale = pulseScale; self.zoomBass = zoomBass; self.rotateTreble = rotateTreble
        self.pulseBass = pulseBass; self.bloomStrength = bloomStrength; self.waveformStrength = waveformStrength
        self.flow = flow; self.flowScale = flowScale; self.beatFlow = beatFlow
        self.beatBloom = beatBloom; self.hueDrift = hueDrift
        self.waveStyle = waveStyle; self.waveAmp = waveAmp; self.waveBright = waveBright; self.tunnel = tunnel
        self.symmetry = symmetry; self.vibrance = vibrance
        self.spin = spin; self.beatWave = beatWave
        self.swirl = swirl; self.swirlFreq = swirlFreq; self.warpMode = warpMode
        self.kaleido = kaleido; self.spokes = spokes; self.spokeLen = spokeLen
        self.spokeInject = spokeInject; self.whirl = whirl
        self.lattice = lattice; self.latticeR = latticeR; self.latticeA = latticeA; self.wash = wash
        self.fractal = fractal; self.cells = cells; self.spiral = spiral
        self.tile = tile; self.pixelate = pixelate; self.truchet = truchet
        self.tunnel3d = tunnel3d; self.plasma = plasma; self.phyllo = phyllo
        self.ripple = ripple; self.hex = hex; self.chroma = chroma
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        version = try c.decode(Int.self, forKey: .version)
        id = try c.decode(String.self, forKey: .id)
        name = try c.decode(String.self, forKey: .name)
        author = try c.decode(String.self, forKey: .author)
        license = try c.decodeIfPresent(String.self, forKey: .license)
        decay = try c.decode(Float.self, forKey: .decay)
        zoom = try c.decode(Float.self, forKey: .zoom)
        rotate = try c.decode(Float.self, forKey: .rotate)
        paletteIndex = try c.decode(Int.self, forKey: .paletteIndex)
        paletteShift = try c.decode(Float.self, forKey: .paletteShift)
        pulseScale = try c.decode(Float.self, forKey: .pulseScale)
        zoomBass = try c.decode(Float.self, forKey: .zoomBass)
        rotateTreble = try c.decode(Float.self, forKey: .rotateTreble)
        pulseBass = try c.decode(Float.self, forKey: .pulseBass)
        bloomStrength = try c.decodeIfPresent(Float.self, forKey: .bloomStrength) ?? 0
        waveformStrength = try c.decodeIfPresent(Float.self, forKey: .waveformStrength) ?? 0
        flow = try c.decodeIfPresent(Float.self, forKey: .flow) ?? 0
        flowScale = try c.decodeIfPresent(Float.self, forKey: .flowScale) ?? 2.5
        beatFlow = try c.decodeIfPresent(Float.self, forKey: .beatFlow) ?? 0
        beatBloom = try c.decodeIfPresent(Float.self, forKey: .beatBloom) ?? 0
        hueDrift = try c.decodeIfPresent(Float.self, forKey: .hueDrift) ?? 0
        waveStyle = try c.decodeIfPresent(Int.self, forKey: .waveStyle) ?? 0
        waveAmp = try c.decodeIfPresent(Float.self, forKey: .waveAmp) ?? 0
        waveBright = try c.decodeIfPresent(Float.self, forKey: .waveBright) ?? 0
        tunnel = try c.decodeIfPresent(Float.self, forKey: .tunnel) ?? 0
        symmetry = try c.decodeIfPresent(Int.self, forKey: .symmetry) ?? 0
        vibrance = try c.decodeIfPresent(Float.self, forKey: .vibrance) ?? 1.0
        spin = try c.decodeIfPresent(Float.self, forKey: .spin) ?? 0
        beatWave = try c.decodeIfPresent(Float.self, forKey: .beatWave) ?? 0
        swirl = try c.decodeIfPresent(Float.self, forKey: .swirl) ?? 0
        swirlFreq = try c.decodeIfPresent(Float.self, forKey: .swirlFreq) ?? 8
        warpMode = try c.decodeIfPresent(Int.self, forKey: .warpMode) ?? 0
        kaleido = try c.decodeIfPresent(Int.self, forKey: .kaleido) ?? 0
        spokes = try c.decodeIfPresent(Int.self, forKey: .spokes) ?? 0
        spokeLen = try c.decodeIfPresent(Float.self, forKey: .spokeLen) ?? 0
        spokeInject = try c.decodeIfPresent(Int.self, forKey: .spokeInject) ?? 0
        whirl = try c.decodeIfPresent(Float.self, forKey: .whirl) ?? 0
        lattice = try c.decodeIfPresent(Float.self, forKey: .lattice) ?? 0
        latticeR = try c.decodeIfPresent(Float.self, forKey: .latticeR) ?? 12
        latticeA = try c.decodeIfPresent(Float.self, forKey: .latticeA) ?? 16
        wash = try c.decodeIfPresent(Float.self, forKey: .wash) ?? 0
        fractal = try c.decodeIfPresent(Int.self, forKey: .fractal) ?? 0
        cells = try c.decodeIfPresent(Float.self, forKey: .cells) ?? 0
        spiral = try c.decodeIfPresent(Float.self, forKey: .spiral) ?? 0
        tile = try c.decodeIfPresent(Float.self, forKey: .tile) ?? 0
        pixelate = try c.decodeIfPresent(Float.self, forKey: .pixelate) ?? 0
        truchet = try c.decodeIfPresent(Float.self, forKey: .truchet) ?? 0
        tunnel3d = try c.decodeIfPresent(Float.self, forKey: .tunnel3d) ?? 0
        plasma = try c.decodeIfPresent(Float.self, forKey: .plasma) ?? 0
        phyllo = try c.decodeIfPresent(Float.self, forKey: .phyllo) ?? 0
        ripple = try c.decodeIfPresent(Float.self, forKey: .ripple) ?? 0
        hex = try c.decodeIfPresent(Float.self, forKey: .hex) ?? 0
        chroma = try c.decodeIfPresent(Float.self, forKey: .chroma) ?? 0
    }

    static let fallback = PermissivePreset(
        version: 1, id: "fallback", name: "Fallback", author: "Vibrdrome", license: "permissive-tbd",
        decay: 0.94, zoom: 0.03, rotate: 0.02, paletteIndex: 0, paletteShift: 0,
        pulseScale: 0.6, zoomBass: 0.7, rotateTreble: 0.4, pulseBass: 0.85,
        bloomStrength: 0.25, waveformStrength: 0)
}

// swiftlint:disable type_body_length
/// Inline DEBUG preset library — the prototype's preset source. NOT a bundled
/// resource. Matches the docs example presets.
enum PermissivePresetLibrary {
    static let json = """
      [
        {
          "version": 1,
          "id": "vibrdrome_flux",
          "name": "Flux",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.94,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 2,
          "paletteShift": 0.0,
          "pulseScale": 0.3,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.55,
          "waveformStrength": 0.0,
          "flow": 0.0,
          "flowScale": 2.5,
          "beatFlow": 0.0,
          "beatBloom": 0.5,
          "hueDrift": 0.4,
          "waveStyle": 1,
          "waveAmp": 0.16,
          "waveBright": 0.95,
          "tunnel": 1.0,
          "symmetry": 1,
          "vibrance": 1.4,
          "spin": 0.0,
          "beatWave": 0.8,
          "swirl": 0.25,
          "swirlFreq": 8.0,
          "warpMode": 1
        },
        {
          "version": 1,
          "id": "vibrdrome_kaleidoscope",
          "name": "Kaleidoscope",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.94,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 5,
          "paletteShift": 0.0,
          "pulseScale": 0.3,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.55,
          "waveformStrength": 0.0,
          "flow": 0.6,
          "flowScale": 3.0,
          "beatFlow": 1.0,
          "beatBloom": 0.5,
          "hueDrift": 0.35,
          "waveStyle": 2,
          "waveAmp": 0.3,
          "waveBright": 1.0,
          "tunnel": 0.6,
          "symmetry": 0,
          "vibrance": 1.4,
          "spin": 0.0,
          "beatWave": 1.0,
          "swirl": 0.25,
          "swirlFreq": 8.0,
          "warpMode": 0,
          "kaleido": 6
        },
        {
          "version": 1,
          "id": "vibrdrome_radiant",
          "name": "Radiant",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.9,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 6,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.5,
          "waveformStrength": 0.0,
          "flow": 0.3,
          "flowScale": 2.5,
          "beatFlow": 0.5,
          "beatBloom": 0.5,
          "hueDrift": 0.3,
          "waveStyle": 0,
          "waveAmp": 0.0,
          "waveBright": 0.0,
          "tunnel": 0.4,
          "symmetry": 0,
          "vibrance": 1.5,
          "spin": 0.0,
          "beatWave": 0.0,
          "swirl": 0.0,
          "swirlFreq": 8.0,
          "warpMode": 0,
          "kaleido": 0,
          "spokes": 16,
          "spokeLen": 0.5
        },
        {
          "version": 1,
          "id": "vibrdrome_spectralspokes",
          "name": "Spectral Spokes",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.96,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 6,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.65,
          "waveformStrength": 0.0,
          "flow": 0.25,
          "flowScale": 2.5,
          "beatFlow": 0.5,
          "beatBloom": 0.6,
          "hueDrift": 0.3,
          "waveStyle": 1,
          "waveAmp": 0.12,
          "waveBright": 0.8,
          "tunnel": 0.75,
          "symmetry": 1,
          "vibrance": 1.5,
          "spin": 0.0,
          "beatWave": 0.6,
          "swirl": 0.0,
          "swirlFreq": 8.0,
          "warpMode": 0,
          "kaleido": 0,
          "spokes": 16,
          "spokeLen": 0.5,
          "spokeInject": 1,
          "whirl": 0.85
        },
        {
          "version": 1,
          "id": "vibrdrome_rosette",
          "name": "Rosette",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.94,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 8,
          "paletteShift": 0.0,
          "pulseScale": 0.25,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.55,
          "waveformStrength": 0.0,
          "flow": 0.55,
          "flowScale": 3.0,
          "beatFlow": 0.6,
          "beatBloom": 0.5,
          "hueDrift": 0.3,
          "waveStyle": 2,
          "waveAmp": 0.3,
          "waveBright": 0.9,
          "tunnel": 0.5,
          "symmetry": 0,
          "vibrance": 1.45,
          "spin": 0.0,
          "beatWave": 0.0,
          "swirl": 0.0,
          "swirlFreq": 8.0,
          "warpMode": 0,
          "kaleido": 8,
          "spokes": 12,
          "spokeLen": 0.4,
          "spokeInject": 0,
          "whirl": 0.0
        },
        {
          "version": 1,
          "id": "vibrdrome_supernova",
          "name": "Supernova",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.95,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 9,
          "paletteShift": 0.0,
          "pulseScale": 0.25,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.6,
          "waveformStrength": 0.0,
          "flow": 0.0,
          "flowScale": 2.5,
          "beatFlow": 0.0,
          "beatBloom": 0.7,
          "hueDrift": 0.4,
          "waveStyle": 1,
          "waveAmp": 0.18,
          "waveBright": 0.9,
          "tunnel": 0.9,
          "symmetry": 1,
          "vibrance": 1.6,
          "spin": 0.06,
          "beatWave": 0.8,
          "swirl": 0.4,
          "swirlFreq": 10.0,
          "warpMode": 1,
          "kaleido": 6,
          "spokes": 18,
          "spokeLen": 0.5,
          "spokeInject": 1,
          "whirl": 0.6
        },
        {
          "version": 1,
          "id": "vibrdrome_moire",
          "name": "Moiré",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.95,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 2,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.5,
          "waveformStrength": 0.0,
          "flow": 0.0,
          "flowScale": 2.5,
          "beatFlow": 0.0,
          "beatBloom": 0.5,
          "hueDrift": 0.3,
          "waveStyle": 0,
          "waveAmp": 0.0,
          "waveBright": 0.0,
          "tunnel": 0.7,
          "symmetry": 1,
          "vibrance": 1.5,
          "spin": 0.0,
          "beatWave": 0.0,
          "swirl": 0.3,
          "swirlFreq": 8.0,
          "warpMode": 1,
          "kaleido": 0,
          "spokes": 0,
          "spokeLen": 0.0,
          "spokeInject": 0,
          "whirl": 0.4,
          "lattice": 0.85,
          "latticeR": 14.0,
          "latticeA": 22.0,
          "wash": 0.0
        },
        {
          "version": 1,
          "id": "vibrdrome_washout",
          "name": "Washout",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.96,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 9,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.6,
          "waveformStrength": 0.0,
          "flow": 0.25,
          "flowScale": 2.5,
          "beatFlow": 0.5,
          "beatBloom": 0.6,
          "hueDrift": 0.3,
          "waveStyle": 1,
          "waveAmp": 0.12,
          "waveBright": 0.8,
          "tunnel": 0.8,
          "symmetry": 1,
          "vibrance": 1.5,
          "spin": 0.0,
          "beatWave": 0.6,
          "swirl": 0.0,
          "swirlFreq": 8.0,
          "warpMode": 0,
          "kaleido": 0,
          "spokes": 18,
          "spokeLen": 0.5,
          "spokeInject": 1,
          "whirl": 0.7,
          "lattice": 0.0,
          "latticeR": 12.0,
          "latticeA": 16.0,
          "wash": 0.55
        },
        {
          "version": 1,
          "id": "vibrdrome_fractalia",
          "name": "Fractalia",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.96,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 6,
          "paletteShift": 0.0,
          "pulseScale": 0.25,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.5,
          "waveformStrength": 0.0,
          "flow": 0.0,
          "flowScale": 2.5,
          "beatFlow": 0.0,
          "beatBloom": 0.6,
          "hueDrift": 0.35,
          "waveStyle": 1,
          "waveAmp": 0.12,
          "waveBright": 0.8,
          "tunnel": 0.6,
          "symmetry": 1,
          "vibrance": 1.55,
          "spin": 0.0,
          "beatWave": 0.5,
          "swirl": 0.3,
          "swirlFreq": 9.0,
          "warpMode": 1,
          "kaleido": 6,
          "spokes": 0,
          "spokeLen": 0.0,
          "spokeInject": 0,
          "whirl": 0.3,
          "lattice": 0.0,
          "latticeR": 12.0,
          "latticeA": 16.0,
          "wash": 0.2,
          "fractal": 5,
          "cells": 0.0
        },
        {
          "version": 1,
          "id": "vibrdrome_liquid",
          "name": "Liquid",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.88,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 6,
          "paletteShift": 0.0,
          "pulseScale": 0.15,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.5,
          "waveformStrength": 0.0,
          "flow": 0.1,
          "flowScale": 2.5,
          "beatFlow": 0.0,
          "beatBloom": 0.5,
          "hueDrift": 0.3,
          "waveStyle": 0,
          "waveAmp": 0.0,
          "waveBright": 0.0,
          "tunnel": 0.0,
          "symmetry": 0,
          "vibrance": 1.5,
          "spin": 0.0,
          "beatWave": 0.0,
          "swirl": 0.0,
          "swirlFreq": 8.0,
          "warpMode": 0,
          "kaleido": 0,
          "spokes": 0,
          "spokeLen": 0.0,
          "spokeInject": 0,
          "whirl": 0.0,
          "lattice": 0.0,
          "latticeR": 12.0,
          "latticeA": 16.0,
          "wash": 0.0,
          "fractal": 0,
          "cells": 1.2
        },
        {
          "version": 1,
          "id": "vibrdrome_singularity",
          "name": "Singularity",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.95,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 6,
          "paletteShift": 0.0,
          "pulseScale": 0.25,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.6,
          "waveformStrength": 0.0,
          "flow": 0.0,
          "flowScale": 2.5,
          "beatFlow": 0.0,
          "beatBloom": 0.7,
          "hueDrift": 0.4,
          "waveStyle": 1,
          "waveAmp": 0.15,
          "waveBright": 0.9,
          "tunnel": 0.8,
          "symmetry": 1,
          "vibrance": 1.6,
          "spin": 0.05,
          "beatWave": 0.6,
          "swirl": 0.4,
          "swirlFreq": 10.0,
          "warpMode": 1,
          "kaleido": 6,
          "spokes": 14,
          "spokeLen": 0.5,
          "spokeInject": 1,
          "whirl": 0.5,
          "lattice": 0.4,
          "latticeR": 12.0,
          "latticeA": 18.0,
          "wash": 0.3,
          "fractal": 3,
          "cells": 0.4
        },
        {
          "version": 1,
          "id": "vibrdrome_orbital",
          "name": "Orbital",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.94,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 6,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.5,
          "waveformStrength": 0.0,
          "flow": 0.0,
          "flowScale": 2.5,
          "beatFlow": 0.0,
          "beatBloom": 0.5,
          "hueDrift": 0.3,
          "waveStyle": 0,
          "waveAmp": 0.0,
          "waveBright": 0.0,
          "tunnel": 0.4,
          "symmetry": 1,
          "vibrance": 1.5,
          "spin": 0.0,
          "beatWave": 0.0,
          "swirl": 0.2,
          "swirlFreq": 8.0,
          "warpMode": 1,
          "kaleido": 8,
          "spokes": 12,
          "spokeLen": 0.4,
          "spokeInject": 0,
          "whirl": 0.2,
          "lattice": 0.7,
          "latticeR": 18.0,
          "latticeA": 24.0,
          "wash": 0.2,
          "fractal": 0,
          "cells": 0.0,
          "spiral": 0.0
        },
        {
          "version": 1,
          "id": "vibrdrome_cubist",
          "name": "Cubist",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.92,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 5,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.45,
          "vibrance": 1.5,
          "warpMode": 0,
          "flow": 0.5,
          "flowScale": 3.0,
          "waveStyle": 1,
          "waveAmp": 0.15,
          "waveBright": 0.7,
          "pixelate": 24.0
        },
        {
          "version": 1,
          "id": "vibrdrome_circuit",
          "name": "Circuit",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.93,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 7,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.5,
          "vibrance": 1.5,
          "warpMode": 0,
          "flow": 0.3,
          "symmetry": 1,
          "truchet": 0.9
        },
        {
          "version": 1,
          "id": "vibrdrome_glitch",
          "name": "Glitch",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.9,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 6,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.45,
          "vibrance": 1.5,
          "warpMode": 0,
          "flow": 0.2,
          "waveStyle": 1,
          "waveAmp": 0.12,
          "waveBright": 0.7,
          "pixelate": 32.0,
          "lattice": 0.6,
          "latticeR": 16.0,
          "latticeA": 20.0,
          "wash": 0.3
        },
        {
          "version": 1,
          "id": "vibrdrome_prismatic",
          "name": "Prismatic",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.94,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 9,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.5,
          "vibrance": 1.5,
          "warpMode": 0,
          "flow": 0.3,
          "tunnel": 0.4,
          "symmetry": 2,
          "waveStyle": 1,
          "waveAmp": 0.2,
          "waveBright": 0.9,
          "tile": 2.0
        },
        {
          "version": 1,
          "id": "vibrdrome_gridlock",
          "name": "Gridlock",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.94,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 8,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.5,
          "vibrance": 1.5,
          "warpMode": 1,
          "swirl": 0.2,
          "symmetry": 1,
          "spokes": 12,
          "spokeLen": 0.4,
          "lattice": 0.8,
          "latticeR": 14.0,
          "latticeA": 18.0,
          "tile": 2.0
        },
        {
          "version": 1,
          "id": "vibrdrome_shatter",
          "name": "Shatter",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.95,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 4,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.6,
          "vibrance": 1.55,
          "warpMode": 1,
          "swirl": 0.3,
          "symmetry": 1,
          "waveStyle": 1,
          "waveAmp": 0.12,
          "waveBright": 0.8,
          "pixelate": 20.0,
          "fractal": 4
        },
        {
          "version": 1,
          "id": "vibrdrome_weave",
          "name": "Weave",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.94,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 7,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.5,
          "vibrance": 1.5,
          "warpMode": 0,
          "flow": 0.3,
          "symmetry": 1,
          "tile": 2.0,
          "truchet": 0.8,
          "wash": 0.35
        },
        {
          "version": 1,
          "id": "vibrdrome_quasar",
          "name": "Quasar",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.95,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 6,
          "paletteShift": 0.0,
          "pulseScale": 0.25,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.6,
          "vibrance": 1.6,
          "warpMode": 1,
          "swirl": 0.3,
          "whirl": 0.4,
          "symmetry": 1,
          "waveStyle": 1,
          "waveAmp": 0.15,
          "waveBright": 0.9,
          "spokes": 14,
          "spokeLen": 0.5,
          "spokeInject": 1,
          "tile": 2.0,
          "truchet": 0.4,
          "lattice": 0.4,
          "latticeR": 12.0,
          "latticeA": 16.0
        },
        {
          "version": 1,
          "id": "vibrdrome_spectrum",
          "name": "Spectrum",
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "decay": 0.9,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteIndex": 6,
          "paletteShift": 0.5,
          "pulseScale": 0.3,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "bloomStrength": 0.7,
          "waveformStrength": 0.0,
          "flow": 0.5,
          "flowScale": 2.5,
          "beatFlow": 1.2,
          "beatBloom": 0.8,
          "hueDrift": 0.5,
          "waveStyle": 2,
          "waveAmp": 0.35,
          "waveBright": 1.0,
          "tunnel": 0.6,
          "symmetry": 2,
          "vibrance": 1.6,
          "spin": 0.15,
          "beatWave": 1.5
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_penrose",
          "name": "Penrose",
          "decay": 0.94,
          "paletteIndex": 7,
          "bloomStrength": 0.5,
          "vibrance": 1.5,
          "warpMode": 1,
          "swirl": 0.2,
          "symmetry": 1,
          "kaleido": 10,
          "spiral": 0.55,
          "tile": 3.0,
          "waveStyle": 1,
          "waveAmp": 0.1,
          "waveBright": 0.8
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_starburst",
          "name": "Starburst",
          "decay": 0.94,
          "paletteIndex": 6,
          "bloomStrength": 0.7,
          "vibrance": 1.55,
          "warpMode": 0,
          "flow": 0.1,
          "symmetry": 1,
          "tunnel": 0.5,
          "spokes": 28,
          "spokeLen": 0.65,
          "spokeInject": 1,
          "whirl": 0.2
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_inkflow",
          "name": "Inkflow",
          "decay": 0.95,
          "paletteIndex": 10,
          "bloomStrength": 0.4,
          "vibrance": 1.6,
          "warpMode": 0,
          "flow": 0.5,
          "symmetry": 1,
          "fractal": 3
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_quadwave",
          "name": "Quadwave",
          "decay": 0.94,
          "paletteIndex": 4,
          "bloomStrength": 0.55,
          "vibrance": 1.55,
          "warpMode": 0,
          "flow": 0.3,
          "symmetry": 2,
          "waveStyle": 1,
          "waveAmp": 0.18,
          "waveBright": 0.9,
          "tile": 2.0,
          "lattice": 0.4,
          "latticeR": 12.0,
          "latticeA": 16.0
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_eclipse",
          "name": "Eclipse",
          "decay": 0.95,
          "paletteIndex": 2,
          "bloomStrength": 0.6,
          "vibrance": 1.6,
          "warpMode": 1,
          "swirl": 0.35,
          "symmetry": 1,
          "spin": 0.04,
          "spokes": 16,
          "spokeLen": 0.5,
          "spokeInject": 1,
          "whirl": 0.5,
          "wash": 0.25,
          "waveStyle": 1,
          "waveAmp": 0.15,
          "waveBright": 0.9,
          "tunnel": 0.8,
          "beatWave": 0.6
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_plasmafield",
          "name": "Plasma",
          "decay": 0.9,
          "paletteIndex": 6,
          "bloomStrength": 0.4,
          "vibrance": 1.55,
          "symmetry": 0,
          "plasma": 1.0
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_wormhole",
          "name": "Wormhole",
          "decay": 0.9,
          "paletteIndex": 8,
          "bloomStrength": 0.55,
          "vibrance": 1.55,
          "symmetry": 0,
          "tunnel3d": 1.0,
          "chroma": 0.5
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_sunflower",
          "name": "Sunflower",
          "decay": 0.92,
          "paletteIndex": 9,
          "bloomStrength": 0.55,
          "vibrance": 1.55,
          "symmetry": 1,
          "whirl": 0.2,
          "phyllo": 1.0
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_pond",
          "name": "Pond",
          "decay": 0.9,
          "paletteIndex": 8,
          "bloomStrength": 0.45,
          "vibrance": 1.55,
          "symmetry": 1,
          "ripple": 1.0
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_honeycomb",
          "name": "Honeycomb",
          "decay": 0.9,
          "paletteIndex": 7,
          "bloomStrength": 0.45,
          "vibrance": 1.55,
          "warpMode": 0,
          "flow": 0.2,
          "symmetry": 1,
          "hex": 1.0
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_datamosh",
          "name": "Datamosh",
          "decay": 0.9,
          "paletteIndex": 6,
          "bloomStrength": 0.45,
          "vibrance": 1.55,
          "warpMode": 0,
          "flow": 0.4,
          "waveStyle": 1,
          "waveAmp": 0.15,
          "waveBright": 0.8,
          "pixelate": 28.0,
          "chroma": 1.2
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_hyperdrive",
          "name": "Hyperdrive",
          "decay": 0.92,
          "paletteIndex": 4,
          "bloomStrength": 0.6,
          "vibrance": 1.6,
          "symmetry": 0,
          "tunnel3d": 0.9,
          "chroma": 0.8
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_lotus",
          "name": "Lotus",
          "decay": 0.93,
          "paletteIndex": 5,
          "bloomStrength": 0.55,
          "vibrance": 1.55,
          "symmetry": 1,
          "kaleido": 6,
          "spiral": 0.4,
          "phyllo": 0.8
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_interzone",
          "name": "Interzone",
          "decay": 0.93,
          "paletteIndex": 2,
          "bloomStrength": 0.5,
          "vibrance": 1.55,
          "symmetry": 1,
          "ripple": 0.7,
          "plasma": 0.6,
          "chroma": 0.5
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_prismfold",
          "name": "Prismfold",
          "decay": 0.93,
          "paletteIndex": 6,
          "bloomStrength": 0.55,
          "vibrance": 1.6,
          "warpMode": 1,
          "swirl": 0.3,
          "symmetry": 1,
          "kaleido": 6,
          "hex": 0.8,
          "chroma": 0.7
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_voidstar",
          "name": "Voidstar",
          "decay": 0.9,
          "paletteIndex": 8,
          "bloomStrength": 0.55,
          "vibrance": 1.55,
          "symmetry": 0,
          "tunnel3d": 0.85,
          "phyllo": 0.5,
          "chroma": 0.5
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_bismuth",
          "name": "Bismuth",
          "decay": 0.9,
          "paletteIndex": 10,
          "bloomStrength": 0.45,
          "vibrance": 1.6,
          "symmetry": 1,
          "hex": 0.9,
          "plasma": 0.5
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_coral",
          "name": "Coral",
          "decay": 0.94,
          "paletteIndex": 5,
          "bloomStrength": 0.5,
          "vibrance": 1.55,
          "warpMode": 0,
          "flow": 0.4,
          "symmetry": 1,
          "cells": 0.8,
          "ripple": 0.5
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_tangerine",
          "name": "Tangerine",
          "decay": 0.9,
          "paletteIndex": 9,
          "bloomStrength": 0.45,
          "vibrance": 1.55,
          "symmetry": 0,
          "plasma": 0.9,
          "chroma": 0.6
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_cryo",
          "name": "Cryo",
          "decay": 0.9,
          "paletteIndex": 8,
          "bloomStrength": 0.45,
          "vibrance": 1.55,
          "symmetry": 1,
          "ripple": 0.7,
          "hex": 0.6
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_mandala2",
          "name": "Mandala",
          "decay": 0.95,
          "paletteIndex": 7,
          "bloomStrength": 0.5,
          "vibrance": 1.55,
          "warpMode": 1,
          "swirl": 0.3,
          "symmetry": 1,
          "kaleido": 6,
          "fractal": 4,
          "spiral": 0.5,
          "waveStyle": 1,
          "waveAmp": 0.1,
          "waveBright": 0.8
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_neuron",
          "name": "Neuron",
          "decay": 0.92,
          "paletteIndex": 10,
          "bloomStrength": 0.4,
          "vibrance": 1.6,
          "warpMode": 0,
          "flow": 0.3,
          "symmetry": 0,
          "truchet": 0.9,
          "cells": 0.5
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_sundial",
          "name": "Sundial",
          "decay": 0.94,
          "paletteIndex": 4,
          "bloomStrength": 0.55,
          "vibrance": 1.55,
          "symmetry": 1,
          "whirl": 0.3,
          "phyllo": 0.8,
          "spokes": 16,
          "spokeLen": 0.5,
          "spokeInject": 1
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_vapor",
          "name": "Vapor",
          "decay": 0.95,
          "paletteIndex": 2,
          "bloomStrength": 0.5,
          "vibrance": 1.55,
          "warpMode": 0,
          "flow": 0.5,
          "symmetry": 1,
          "plasma": 0.6,
          "wash": 0.4
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_kaleidotunnel",
          "name": "Kaleidotunnel",
          "decay": 0.9,
          "paletteIndex": 6,
          "bloomStrength": 0.55,
          "vibrance": 1.55,
          "symmetry": 2,
          "kaleido": 6,
          "tunnel3d": 0.8,
          "chroma": 0.3
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_fissure",
          "name": "Fissure",
          "decay": 0.92,
          "paletteIndex": 4,
          "bloomStrength": 0.5,
          "vibrance": 1.55,
          "warpMode": 0,
          "flow": 0.3,
          "cells": 0.7,
          "chroma": 0.7,
          "pixelate": 24.0
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_halo",
          "name": "Halo",
          "decay": 0.93,
          "paletteIndex": 8,
          "bloomStrength": 0.5,
          "vibrance": 1.55,
          "warpMode": 1,
          "swirl": 0.2,
          "symmetry": 1,
          "ripple": 0.6,
          "lattice": 0.6,
          "latticeR": 14.0,
          "latticeA": 18.0,
          "spokes": 12,
          "spokeLen": 0.4
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_mercury",
          "name": "Mercury",
          "decay": 0.94,
          "paletteIndex": 10,
          "bloomStrength": 0.5,
          "vibrance": 1.6,
          "warpMode": 1,
          "swirl": 0.35,
          "symmetry": 1,
          "whirl": 0.3,
          "plasma": 0.7,
          "chroma": 0.6
        },
        {
          "version": 1,
          "zoom": 0.0,
          "rotate": 0.0,
          "paletteShift": 0.0,
          "pulseScale": 0.2,
          "zoomBass": 0.0,
          "rotateTreble": 0.0,
          "pulseBass": 0.0,
          "author": "Vibrdrome",
          "license": "permissive-tbd",
          "id": "vibrdrome_zenith",
          "name": "Zenith",
          "decay": 0.95,
          "paletteIndex": 2,
          "bloomStrength": 0.6,
          "vibrance": 1.6,
          "warpMode": 1,
          "swirl": 0.3,
          "symmetry": 1,
          "whirl": 0.3,
          "kaleido": 6,
          "tunnel3d": 0.5,
          "phyllo": 0.4,
          "spiral": 0.4,
          "chroma": 0.4,
          "waveStyle": 1,
          "waveAmp": 0.12,
          "waveBright": 0.85
        }
      ]
    """

    static let presets: [PermissivePreset] = {
        (try? JSONDecoder().decode([PermissivePreset].self, from: Data(json.utf8))) ?? []
    }()
}
// swiftlint:enable type_body_length
#endif
